// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class EmbeddedControllerZPosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmbeddedControllerZPosition));
        
        string IMigrationMetadata.Id
        {
            get { return "202004292158075_EmbeddedControllerZPosition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
